### ISSUE TITLE
readMe mist beschrijving 

### ISSUE THREAD

**Issue by SamSlotemaker** [RowinRuizendaal/real-time-web-2021#1]
App beschrijving mist en eigenlijk vrijwel alle andere beschrijvingen, zoals externa data, real time events, etc.

**Comment by SamSlotemaker** [comment]
Oh app beschrijving is er wel, sorry :)

**Comment by RowinRuizendaal** [comment]
Bedankt voor je review, ik heb real-time events toegevoegd
