### ISSUE TITLE
Lost instantly, not enough time to move

### ISSUE THREAD

**Issue by standrd** [RowinRuizendaal/real-time-web-2021#19]
It seems like the speed is very high, I couldn't even move before already losing the game.

Maybe consider showing the snakes on the countdown, so the user knows where their snake is.

**Comment by RowinRuizendaal** [comment]
Hmm, not sure how this happens since the snakes are kinda slow for me to move, I will dive into this

**Comment by RowinRuizendaal** [comment]
Dropped the framerate
