### ISSUE TITLE
Data flowchart niet volledig

### ISSUE THREAD

**Issue by SamSlotemaker** [RowinRuizendaal/real-time-web-2021#2]
Het lijkt er naar mij op dat de flow in je chart niet helemaal correct is. Er wordt bijvoorbeeld vanuit de server een nieuwe positie gereturned, alleen lijkt het er op deze manier op dat deze nooit bij de client terecht komt

**Comment by RowinRuizendaal** [comment]
bedankt voor je feedback, de nieuwe positite wordt inderdaad niet terug gestuurd naar de client, de client geeft alleen aan de server aan welke kant de slang opgaat, de server houdt dus per room aan waar de slang zich bevind :)
