### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by standrd** [RowinRuizendaal/real-time-web-2021#3]
### Repository
* Repository heeft nu nog de standaard RTW naam, als je een naam voor je project hebt kun je die aanpassen in de settings
* Er is een beschrijving van het concept aanwezig die erg goed is
* Live link is aanwezig
* Ik zou code meer bundelen in een /src folder. Nu staan er losse .js bestanden in de root
* Er is een dataflow aanwezig, maar voor de rest nog geen API beschrijving, real-time events or install notes

### Concept
* Ik begrijp wat de app doet vanuit de beschrijving
* De app staat live en werkt ook al voor een best groot deel. Ik kon zelf het spel niet in mijn eentje spelen, maar ik kon wel al in een room en zag op 1 scherm dat ik won en op het andere scherm dat ik verloor
* Ik denk als je dit goed werkend krijgt dat er weinig meer aan toegevoegt hoeft te worden, het zou zo al super vet zijn!

### Data life cycle
Data life cycle is uitgebreid, ik zie alleen niet gelijk het verschil tussen API calls & websockets verbindingen. Dit zou nog beter kunnen met kleuren

### Real-time events
Nog niet aanwezig.

### API info
Nog niet aanwezig

## Code comments
* Ik vind het heel netjes opgezet met duidelijk onderscheid tussen normale variables en de constantes van de game (in ALL CAPS)
* Er zijn wel veel (vind ik) onnodige enters in de code, maar ik begrijp dat dit per persoon verschilt
* Misschien zou je nog kunnen kijken naar Babel om ES6 import en export bijvoorbeeld te gebruiken

**Comment by RowinRuizendaal** [comment]
Hoi Stan,

Bedankt voor je feedback

- [x] Repo naam veranderd naar multiplayer snake game
- [x] Real-time event toegevoegd
- [x] install notes toegevoegd
- [x] data life cycle aangepast
